version: '3.7'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-1
    networks:
      - kafka-net
    ports:
      - 2181:2181

    deploy:
      placement:
          constraints:
            - node.labels.zoo==1
      restart_policy:
          condition: on-failure
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:2181

  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    networks:
      - kafka-net
    ports:
      - 9093:9093
      - 9092:9092
    depends_on:
      - zookeeper-1
    deploy:
      placement:
        constraints:
          - node.labels.kafka==1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:12181,zookeeper-3:12181
      KAFKA_LISTENERS: INT://:9092,EXT://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INT:PLAINTEXT,EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_ADVERTISED_LISTENERS: INT://:9092,EXT://ec2-3-21-198-203.us-east-2.compute.amazonaws.com:9093


  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    networks:
      - kafka-net
    ports:
      - 9094:9094
      - 19092:19092
    depends_on:
      - zookeeper-1

    deploy:
      placement:
        constraints:
          - node.labels.kafka==2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENERS: INT://:19092,EXT://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INT:PLAINTEXT,EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_ADVERTISED_LISTENERS: INT://:19092,EXT://ec2-3-21-175-113.us-east-2.compute.amazonaws.com:9094

  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    networks:
      - kafka-net
    ports:
      - 9095:9095
      - 29092:29092
    deploy:
      placement:
        constraints:
          - node.labels.kafka==3
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENERS: INT://:29092,EXT://0.0.0.0:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INT:PLAINTEXT,EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_ADVERTISED_LISTENERS: INT://:29092,EXT://ec2-13-58-140-213.us-east-2.compute.amazonaws.com:9095

networks:
  kafka-net:
