version: '3.7'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-1
    networks:
      - kafka-net
    ports:
      - target: 12181
        published: 12181
        protocol: tcp
        mode: host
      - target: 13888
        published: 13888
        protocol: tcp
        mode: host
      - target: 12888
        published: 12888
        protocol: tcp
        mode: host

    deploy:
      placement:
          constraints:
            - node.labels.zoo==1
      restart_policy:
          condition: on-failure
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-2
    networks:
      - kafka-net
    ports:
      - target: 22181
        published: 22181
        protocol: tcp
        mode: host
      - target: 23888
        published: 23888
        protocol: tcp
        mode: host
      - target: 2888
        published: 22888
        protocol: tcp
        mode: host

    deploy:
      placement:
          constraints:
            - node.labels.zoo==2
      restart_policy:
          condition: on-failure
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-3
    networks:
      - kafka-net
    ports:
      - target: 32181
        published: 32181
        protocol: tcp
        mode: host
      - target: 33888
        published: 33888
        protocol: tcp
        mode: host
      - target: 32888
        published: 32888
        protocol: tcp
        mode: host

    deploy:
      placement:
          constraints:
            - node.labels.zoo==3
      restart_policy:
          condition: on-failure
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888

  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    networks:
      - kafka-net
    ports:
      - target: 19092
        published: 19092
        protocol: tcp
        mode: host
      - target: 19093
        published: 19093
        protocol: tcp
        mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    deploy:
      placement:
        constraints:
          - node.labels.kafka==1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:12181,zookeeper-3:12181
      KAFKA_LISTENERS: INT://:19093,EXT://0.0.0.0:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INT:PLAINTEXT,EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_ADVERTISED_LISTENERS: INT://:19093,EXT://ec2-3-21-198-203.us-east-2.compute.amazonaws.com:19092


  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    networks:
      - kafka-net
    ports:
      - target: 29092
        published: 29092
        protocol: tcp
        mode: host
      - target: 19094
        published: 19094
        protocol: tcp
        mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    deploy:
      placement:
        constraints:
          - node.labels.kafka==2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:12181,zookeeper-3:12181
      KAFKA_LISTENERS: INT://:19094,EXT://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INT:PLAINTEXT,EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_ADVERTISED_LISTENERS: INT://:19094,EXT://ec2-3-21-175-113.us-east-2.compute.amazonaws.com:29092

  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    networks:
      - kafka-net
    ports:
      - target: 39092
        published: 39092
        protocol: tcp
        mode: host
      - target: 19095
        published: 19095
        protocol: tcp
        mode: host

    deploy:
      placement:
        constraints:
          - node.labels.kafka==3
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:12181,zookeeper-3:12181
      KAFKA_LISTENERS: INT://:19095,EXT://0.0.0.0:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INT:PLAINTEXT,EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_ADVERTISED_LISTENERS: INT://:19095,EXT://ec2-13-58-140-213.us-east-2.compute.amazonaws.com:39092

networks:
  kafka-net:
